### PR TITLE
Merge acme_develop to master

### LINKED ISSUE #38: Merging acme_develop to master
This issue is to keep track of merging acme_develop
to master.
The acme_develop branch has several fixes, required
to run E3SM with PIO2, and enhancements.

### PR DESCRIPTION
**Pull request by jayeshkrishna**
This PR merges the acme_develop branch to master.

Fixes #38

### CODE REVIEW

**Comment by jayeshkrishna** [comment]
I just reviewed the changes and it looks good to me.

The branch is currently being tested nightly - https://my.cdash.org/index.php?project=ACME_PIO (Look at build "Linux-3.13.0-121-generic-x86_64-gcc-6.2.0-acme_develop_merge2master")

**Comment by dqwu** [comment]
Switched existing cime_developer/acme_developer tests to use acme_develop_merge2master branch.

Some tests failed, see:
https://my.cdash.org/viewTest.php?onlyfailed&buildid=1360587
https://my.cdash.org/viewTest.php?onlyfailed&buildid=1360580
https://my.cdash.org/viewTest.php?onlyfailed&buildid=1360526

I will take a look.

**Comment by jayeshkrishna** [comment]
Are these failures only occurring with this new branch (tests pass with acme_develop/master but fail with acme_develop_merge2master)?

**Comment by dqwu** [comment]
I can fix the cime_developer tests (this branch is OK, only need update the build script).
Will look at the 3 failed acme_developer tests later.

**Comment by dqwu** [comment]
The cime_developer tests can pass now, see:
https://my.cdash.org/viewTest.php?onlypassed&buildid=1360643

I can reproduce the failure of acme_developer test SMS_D_Ln5.ne4_ne4.FC5AV1C-L:
NetCDF: Not a valid ID
Abort with message NetCDF: Not a valid ID in file cime/src/externals/pio2/src/clib/pio_file.c at line 279

Will continue to debug this.

**Comment by dqwu** [comment]
Commit 2406c8b in master branch caches file and variable names in PIO. However, it requires that we use pnetcdf 1.8.1 or higher versions (a bug in prev versions defined NF_MAX_NAME and NC_MAX_NAME as different)

The failed ACME tests uses pnetcdf 1.6.1. We should switch to pnetcdf 1.8.1 for them to pass.

Also, we can add pnetcdf version check as specified in issue #22

**Comment by dqwu** [comment]
Even with pnetcdf 1.8.1 these ACME tests still fail. Looks like a different issue, see #56

**Comment by jayeshkrishna** [comment]
So is this branch ready to go to develop? The above issue seems to be due to code that is already on master.

**Comment by dqwu** [comment]
Yes this branch can be merged to develop for testing.

**Pull request merged**
