### PR TITLE
Adding internal GPTL timing summary

### PR DESCRIPTION
**Pull request by jayeshkrishna**
Adding an option to gather and log GPTL timing
statistics in PIO.

If users build PIO with "PIO_ENABLE_TIMING" and
"PIO_ENABLE_INTERNAL_TIMING" the GPTL timing
statistics is automatically logged into files named
"piorwgptl*.dat"

### CODE REVIEW

**Comment by jayeshkrishna** [comment]
Ok, I can see the timeout (anlworkstation). Let me see what is going on.

**Comment by jayeshkrishna** [comment]
I see the issue here, let me try to fix it and then you can review the PR again.

The issue is that with finalizing global frameworks (e.g. logging etc) we need to keep track of how many times the init/finalize is called since PIO allows initializing for multiple iosystems. See pio_finalize_logging() for example.

**Comment by dqwu** [comment]
There is a build error when PIO_ENABLE_LOGGING is OFF.
```
src/clib/pioc_support.c:178:5: error: ‘pio_timer_ref_cnt’ undeclared (first use in this function)
     pio_timer_ref_cnt += 1;
     ^~~~~~~~~~~~~~~~~
```
This is because pio_timer_ref_cnt is defined inside the code block below:
```
#if PIO_ENABLE_LOGGING
...
#endif /* PIO_ENABLE_LOGGING */
```

**Comment by jayeshkrishna** [comment]
Argh, my bad. Let me fix this and get back to you.

**Comment by jayeshkrishna** [comment]
The issue should be fixed now. Verified that all tests pass on anlworkstation (with/without internal timing, without timing/logging).
I rebased the branch with the fix (Please reset your branch to the remote version).

**Pull request merged**
